<Project>
	<PropertyGroup>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
	</PropertyGroup>
	<ItemGroup>
		<PackageVersion Include="SAL.Flatbed" Version="1.2.12" />
		<!--Source Link Support-->
		<PackageVersion Include="Microsoft.SourceLink.GitHub" Version="8.0.0">
			<PrivateAssets>All</PrivateAssets>
		</PackageVersion>
		<!--Analyzers-->
		<GlobalPackageReference Include="SonarAnalyzer.CSharp" Version="10.26.0.140279">
			<PrivateAssets>All</PrivateAssets>
			<IncludeAssets>Runtime; Build; Native; contentfiles; Analyzers; buildtransitive</IncludeAssets>
		</GlobalPackageReference>
	</ItemGroup>
</Project>